name: Deploy-SRE-BOOTCAMP
on:
  push:
    branches: 
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v7